### ISSUE TITLE
Exclude draft PRs and wip PRs from "Open PRs"

### ISSUE THREAD

**Issue by zmichaels11** [ros-security/github-contribution-report-generator#4]
### Description
- [X] Exclude draft PRs from report
- [ ] Exclude PRs prefixed with `[WIP]`

**Comment by thomas-moulard** [comment]
Draft can be excluded using this syntax: https://github.community/t5/How-to-use-Git-and-GitHub/Pull-Request-filter-for-draft-PRs/td-p/20016
