### ISSUE TITLE
Add an option to configure report names

### ISSUE THREAD

**Issue by zmichaels11** [ros-security/github-contribution-report-generator#8]
Report names are hardcoded as `report.md` and `report.html`
It would be nice to have a parameter to configure these in the use case of a workflow generating multiple reports.

Example:
A single workflow could use this action 3x to generate
* daily report as `daily/report.html`
* weekly report as `weekly/report.html`
* monthly report as `montly/report.html`

**Comment by dabonnie** [comment]
Opened PR: https://github.com/ros-security/github-contribution-report-generator/pull/9

**Comment by zmichaels11** [comment]
A different PR (https://github.com/ros-security/github-contribution-report-generator/pull/12 ) was opened and merged.
